basic/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\widgets\ActiveForm;
use app\models\Users;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\FormularioVendedor;
use yii\helpers\Url;
use yii\helpers\Html;


class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
	
	
	private function randKey($str='', $long=0)
    {
        $key = null;
        $str = str_split($str);
        $start = 0;
        $limit = count($str)-1;
        for($x=0; $x<$long; $x++)
        {
            $key .= $str[rand($start, $limit)];
        }
        return $key;
    }
	
	
	
	
	/** Formulario para el ingreso de los vendedores **/
	public function actionRegister(){
		
		 $model = new FormularioVendedor;

         //Mostrará un mensaje en la vista cuando el usuario se haya registrado
         $msg = null;
   
		//Validación mediante ajax
		if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax)
			{
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
   
		//Validación cuando el formulario es enviado vía post
		//Esto sucede cuando la validación ajax se ha llevado a cabo correctamente
		//También previene por si el usuario tiene desactivado javascript y la
		//validación mediante ajax no puede ser llevada a cabo
		if ($model->load(Yii::$app->request->post()))
		{
			if($model->validate())
			{
			//Preparamos la consulta para guardar el usuario
			$table = new Users;
			$table->Rut = $model->Rut;
			$table->Nombre = $model->Nombre;
			$table->Apellido = $model->Apellido;
			//Encriptamos el password
			$table->Clave =$model->Clave;
			//Creamos una cookie para autenticar al usuario cuando decida recordar la sesión, esta misma
			//clave será utilizada para activar el usuario
			$table->authKey = $this->randKey("abcdef0123456789", 200);
     
			//Si el registro es guardado correctamente
			if ($table->insert())
			{
			
    
    
                $model->Rut = null;
				$model->Nombre = null;
				$model->Apellido = null;
				$model->Clave = null;
				$model->Clave_repeat = null;
     
				$msg = "Registro exitoso";
                 return $this->render('index');
			}
			else
			{
				$msg = "Ha ocurrido un error al llevar a cabo tu registro";
			}
     
		}
		else
	{
      $model->getErrors();
     }
  }
  return $this->render("ingreso", ["model" => $model, "msg" => $msg]);
		
	}
}

basic/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Gestión de Ventas e Inventario Minimarket "San Cristóbal"',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Inicio', 'url' => ['/site/index']],
            ['label' => 'Registro','url' =>['/site/register']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Acceder', 'url' => ['/site/login']]
            ) : (
                
              '<li>'
                . Html::beginForm(['/producto'], 'post')
                . Html::submitButton(
                    'Producto',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'.
               '<li>'
                . Html::beginForm(['/vendedor'], 'post')
                . Html::submitButton(
                    'Vendedor',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'.
                '<li>'
                . Html::beginForm(['/venta'], 'post')
                . Html::submitButton(
                    'Venta',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'.
        '<li>'
                . Html::beginForm(['/compra'], 'post')
                . Html::submitButton(
                    'Compra',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'.
                
        
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->nombre . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
               
        
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; QWERTY Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>